# Generated by Django 4.1.3 on 2022-11-12 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fechaHoraInicio', models.DateField()),
                ('fechaHoraTermino', models.DateField()),
                ('estado', models.IntegerField()),
                ('link', models.TextField(max_length=256)),
                ('agendaAnterior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ArquitecturaAPP.agenda')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=50)),
                ('fechaCreacion', models.DateField()),
                ('estado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=256)),
                ('fechaCreacion', models.DateField()),
                ('estado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=256)),
                ('fechaCreacion', models.DateField()),
                ('estado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=256)),
                ('fechaCreacion', models.DateField()),
                ('estado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=50)),
                ('fechaCreacion', models.DateField()),
                ('estado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fechaPago', models.DateField()),
                ('monto', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('comision', models.IntegerField()),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ArquitecturaAPP.agenda')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ArquitecturaAPP.alumno')),
                ('formaPago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ArquitecturaAPP.formapago')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=256)),
                ('fechaCreacion', models.DateField()),
                ('estado', models.IntegerField()),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ArquitecturaAPP.agenda')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ArquitecturaAPP.alumno')),
            ],
        ),
        migrations.AddField(
            model_name='agenda',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ArquitecturaAPP.asignatura'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='plataforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ArquitecturaAPP.plataforma'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ArquitecturaAPP.profesor'),
        ),
    ]
