# Generated by Django 4.1.3 on 2022-11-27 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArquitecturaAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=256)),
                ('fechaCreacion', models.DateField()),
                ('estado', models.IntegerField()),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ArquitecturaAPP.agenda')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ArquitecturaAPP.alumno')),
            ],
        ),
    ]
