# Generated by Django 4.1.3 on 2022-11-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArquitecturaAPP', '0002_valoracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='fechaHoraInicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='fechaHoraTermino',
            field=models.DateTimeField(),
        ),
    ]
