# Generated by Django 4.1.3 on 2022-11-27 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArquitecturaAPP', '0003_alter_agenda_fechahorainicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='agendaAnterior',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ArquitecturaAPP.agenda'),
        ),
    ]
