# Generated by Django 4.1.3 on 2022-11-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArquitecturaAPP', '0004_alter_agenda_agendaanterior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='descripcion',
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='descripcion',
            field=models.TextField(max_length=256, null=True),
        ),
    ]
